### PR TITLE
Hot fix remembers selected group #46

### PR DESCRIPTION
**Pull request by aviret**
This fix was missing

### CODE REVIEW

**Comment by ThomasDaheim** [comment]
I guess that doesn't always work - e.g. if the new list doesn't contain the old value... The only save thing would to remember the current group and check if its still in the list after the update.

**Comment by aviret** [comment]
The line "selectRow(0);" reset the select group to All (I'm using the classic look & feel). So when you edit a note, starting with a select group, you save it (now with the Ctrl-S (cool !)), then select group is reset to All, so you have to return to your last selection manually).

**Comment by ThomasDaheim** [comment]
Yes, I know. But unfortunately, I don't think your approach works in all possible cases.

**Comment by aviret** [comment]
You are right, if I move the note to another group, and the current group contains no more notes, it is removed from the list. In that case we have to select "All".

**Comment by ThomasDaheim** [comment]
Could you please have a look at my pull-request #49?

**Comment by aviret** [comment]
Your pull request #49 is working. Thanks

**Pull request closed without merging**
