### PR TITLE
UI Candy added

### PR DESCRIPTION
**Pull request by ThomasDaheim**
- Minimize to system tray (if available)
- "+" tab to add a new group in oneNote look & feel

### CODE REVIEW

**Comment by ThomasDaheim** [comment]
* Color notes in oneNote loom & feel according to group color (inital version), see issue #36

**Comment by aviret** [comment]
I have an exception when I have more than 10 groups (in fact I have 23 groups):

Executing /Users/vir/Dev/ownNoteEditor/ownNoteEditor/dist/run2078438109/ownNoteEditor.jar using platform /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/bin/java
...
Found group: Not grouped as number: 1
Found group: AIEM - Done as number: 2
Found group: AIEM - Todo as number: 3
...
Found group: TF - Bug OpenJustitia as number: 10
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: 10
	at tf.ownnote.ui.main.OwnNoteEditor.getGroupColor(OwnNoteEditor.java:1358)
	at tf.ownnote.ui.helper.OwnNoteTabPane.addOwnNoteTab(OwnNoteTabPane.java:171)
	at tf.ownnote.ui.helper.OwnNoteTabPane.setGroups(OwnNoteTabPane.java:213)
	at tf.ownnote.ui.main.OwnNoteEditor.initFromDirectory(OwnNoteEditor.java:809)
	at tf.ownnote.ui.main.OwnNoteEditor.lambda$initEditor$12(OwnNoteEditor.java:714)
...

**Comment by ThomasDaheim** [comment]
Aaargh, you're right - I probably missed the wrap around to start again with the first color...

**Comment by ThomasDaheim** [comment]
Please give that update a try. Seems to work for me.

**Comment by aviret** [comment]
It works for me too !

**Comment by ThomasDaheim** [comment]
Sounds good. If you could please have a look at the other two features too I would merge the pull request:

- Minimize to system tray (if available)
- "+" tab to add a new group in oneNote look & feel

**Comment by aviret** [comment]
- Minimize: has already before on OS X, not seen any difference
- "+" tab: it creates the group, but the original name ("New group 23") stays in the popup list, after the name has been changed and is correctly showed in the tabs.

**Comment by ThomasDaheim** [comment]
Thanks, will have a look at that...

What happens if you rename an existing group? Is the popup updated properly? Not sure what I would do differently for a new group as compared to an existing group...

**Comment by aviret** [comment]
It's the same behavior: the tab name is changed, but the list has the previous name

**Comment by ThomasDaheim** [comment]
I looked around and there seem to be issues with the menu of the javafx tabpane. A few bugs are open for that :-(

Let me see if I can find some way to fix that...

**Comment by aviret** [comment]
Good luck !

**Comment by ThomasDaheim** [comment]
Well, I guess we have to live with that issue... Its really a problem of the javafx tabpane and I would need to do some dirty things to make it work. So I guess we hope that javafx 9 fixes things :-)

**Pull request merged**
