### PR TITLE
create Mac OS X .app bundle and a .dmg file

### PR DESCRIPTION
**Pull request by tessus**
On Mac OS X it is possible to create an app bundle, which allows you to launch the Java application like any other OS X app.

My change includes the following items:
* an application icon
* a plugin in the `build.gradle` file
* instructions in the `README.md` how to create a Mac OS X .app bundle and a .dmg file

## create a Mac OS X .app bundle

```
./gradlew createApp
```

The resulting application will be in the directory `build/macApp`.

## create a Mac OS X .dmg file (will only work on Mac OS X)

```
./gradlew createDmg
```

The resulting file will be in the directory `build/distributions`.

### CODE REVIEW

**Comment by tessus** [comment]
You can download the .dmg file with the Mac OS X application [here](http://g0to.ca/oNE).
If you want, you can create a release on github and attach the .dmg file.

**Comment by ThomasDaheim** [comment]
Where would I need to put the .dmg file?

**Comment by madmas** [comment]
:+1: cool stuff :)
@ThomasDaheim: https://help.github.com/articles/creating-releases/ ;-)

**Comment by tessus** [comment]
@ThomasDaheim when you create a release on github, a snapshot of the current git tree is automatically taken and appended to the release as 2 files named Source Code (zip) and (tar.gz).
Here is an [example](https://github.com/tessus/MongoDB-prefPane/releases/tag/1.3).
But a snapshot of the tree, is not really a release tarball, nor does it help, if you want to provide executables. Therefore you can attach additional files to a release.

In your project, I'd suggest to add 2 additional files. The .dmg file and a zip of the actuall app.
gradle is a great tool to manage code, but you don't want to run it everytime you want to start the app.
e.g. if you do a `./gradlew installApp` you'll get a distributable tree in `build/install`. Or maybe there's a better way.

It's just a suggestion. You don't have to create a release at all.
You can also reference the [download link](http://g0to.ca/oNE) of the .dmg file in the README.md, if you want.
I just thought it would be easier for people, who don't know git or gradle, to have an executable app available.

**Comment by ThomasDaheim** [comment]
Well, let me have a look at the release stuff under the Christmas tree :-)

Thanks for the pull request @tessus!

**Pull request merged**
